name: "JSON Watcher Buildkite Plugin"
description: Simple buildkite plugin to watch for a specific field in a JSON file
author: https://github.com/ninalee12
requirements:
  - jq
  - curl
configuration:
  properties:
    expected_value:
      type: string
      description: The expected value for the JSON field
    field:
      type: string
      description: The jq path to the field (e.g., ".version" or ".app.name.version")
    polling_interval:
      type: number
      description: The polling interval in seconds for the curl
      default: 60
    urls:
      type: string
      description: One or more URLs to poll (comma-separated if multiple)
  required:
    - expected_value
    - field
    - urls
  additionalProperties: false
